package com.maplequad.gbm.grt.om;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-15T12:36:55.705+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "IExecuteService", 
                  wsdlLocation = "http://35.187.82.167:8080/sra-service/Execute?wsdl",
                  targetNamespace = "http://www.maplequad.com/gbm/grt/om") 
public class IExecuteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.maplequad.com/gbm/grt/om", "IExecuteService");
    public final static QName IExecutePort = new QName("http://www.maplequad.com/gbm/grt/om", "IExecutePort");
    static {
        URL url = null;
        try {
            url = new URL("http://35.187.82.167:8080/sra-service/Execute?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IExecuteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://35.187.82.167:8080/sra-service/Execute?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IExecuteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IExecuteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IExecuteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IExecuteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IExecuteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IExecuteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IExecute
     */
    @WebEndpoint(name = "IExecutePort")
    public IExecute getIExecutePort() {
        return super.getPort(IExecutePort, IExecute.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExecute
     */
    @WebEndpoint(name = "IExecutePort")
    public IExecute getIExecutePort(WebServiceFeature... features) {
        return super.getPort(IExecutePort, IExecute.class, features);
    }

}
