package com.maplequad.gbm.grt.om;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-09T13:56:33.737+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "IFeedNotificationService", 
                  wsdlLocation = "http://35.205.201.164:8080/sra-service/FeedNotification?wsdl",
                  targetNamespace = "http://www.maplequad.com/gbm/grt/om") 
public class IFeedNotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.maplequad.com/gbm/grt/om", "IFeedNotificationService");
    public final static QName IFeedNotificationPort = new QName("http://www.maplequad.com/gbm/grt/om", "IFeedNotificationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://35.205.201.164:8080/sra-service/FeedNotification?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IFeedNotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://35.205.201.164:8080/sra-service/FeedNotification?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IFeedNotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IFeedNotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFeedNotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IFeedNotificationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IFeedNotificationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IFeedNotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IFeedNotification
     */
    @WebEndpoint(name = "IFeedNotificationPort")
    public IFeedNotification getIFeedNotificationPort() {
        return super.getPort(IFeedNotificationPort, IFeedNotification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFeedNotification
     */
    @WebEndpoint(name = "IFeedNotificationPort")
    public IFeedNotification getIFeedNotificationPort(WebServiceFeature... features) {
        return super.getPort(IFeedNotificationPort, IFeedNotification.class, features);
    }

}
