package com.maplequad.gbm.grt.om;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-09T13:56:33.587+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.maplequad.com/gbm/grt/om", name = "IFeedNotification")
@XmlSeeAlso({ObjectFactory.class})
public interface IFeedNotification {

    @WebMethod
    @RequestWrapper(localName = "feedNotificationWrapperRequest", targetNamespace = "http://www.maplequad.com/gbm/grt/om", className = "com.maplequad.gbm.grt.om.FeedNotificationWrapperRequest")
    @ResponseWrapper(localName = "feedNotificationWrapperRequestResponse", targetNamespace = "http://www.maplequad.com/gbm/grt/om", className = "com.maplequad.gbm.grt.om.FeedNotificationWrapperRequestResponse")
    @WebResult(name = "FeedNotificationResponse", targetNamespace = "")
    public com.maplequad.gbm.grt.om.FeedNotificationResponse feedNotificationWrapperRequest(
        @WebParam(name = "FeedNotificationRequest", targetNamespace = "")
        com.maplequad.gbm.grt.om.FeedNotificationRequest feedNotificationRequest
    );
}
