package org.jt.opensource
import org.jt.opensource.bean.RuleBean
import java.text.SimpleDateFormat

rule "Rule 01"     
    when 
       bean : RuleBean(amount < 3.0) 
    then  
       System.out.println("HelloWorld" + bean.getDate());
       bean.setAmount(20000);  
       
end

rule "Rule 02"    
   salience 2 
    when 
       bean : RuleBean(amount < 555.0) 
    then  
       System.out.println("it already get the point at 555 for date:" + bean.getDate());
       bean.setAmount(3948);  
       
end

rule "Rule 03"   
    salience 1 
    when 
       bean : RuleBean(amount < 455.0) 
    then  
       System.out.println("it already get the point at 455 for date:" + bean.getDate());
       bean.setAmount(333948);  
       
end



